services:
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run migrate
    volumes:
      - ./backend/data:/usr/src/app/data
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/flashcards?authSource=admin

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 